-- Insertar cursos de ejemplo
INSERT INTO cursos (nombre, descripcion, duracion, instructor, precio, imagen) VALUES
('Máster en Desarrollo Web Full Stack', 'Domina las tecnologías más modernas desde el frontend hasta el backend con proyectos reales y prácticos.', '120 horas', 'Carlos Martínez', 599.00, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBJVCuQrKAmif9jTvB_jKApWD8rMbwho9OYlhTj4wA6YNErdpkUl6KDdlUq2Cw6rTc3OhWlf5GRqHdz_A99Vt2KbQEOQl2p48S1YXlTNsgrlJRxa8GSim5aESXbXpwTfnEsV1aNjzIRdamTrFsTj1Vyj6AN3mA2mvzJuyX8ZJ_0YZzceJgz0uqv6UPeEBC4v-3OCqonlxt0Ov6E_xaAxd3pP0ECrEhV1DUVrcDoXpBSS36NJ61Vk6JPUHXBKmeN-zjJzYN11RfvfeNG'),

('Estrategias de Marketing Digital', 'Aprende a posicionar marcas y aumentar ventas utilizando SEO, SEM y analítica avanzada de datos.', '80 horas', 'Ana García', 449.00, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDl0Nruo_mbwLPXSBInSgpMJVHZnWHDeJrBwzqjkzV3iDpzKCGFoFKMnG5s5fkwRttgZS5BoRc09VyAj345hO_GJ__1t5m2FR1ChM3SpwXDMS79kU95iSXc7LUO2EDsd6irDzJ99Z8CqJfgFEPscJxqJf0-zfj3xZNCVvnQwSYksjtgoEs0kfqIWygZ3uI-JjLlE-2XPN9fPPDbjKnmHUADRZ945Vyd77ll_hzWoG-SqZhQ8f-xI4Gkb3sBuXd7wd5zeeNntGDExVQV'),

('Gestión de Proyectos Ágiles', 'Certifícate en Scrum y Kanban para liderar equipos de alto rendimiento en entornos dinámicos.', '60 horas', 'Miguel Rodríguez', 399.00, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBJVCuQrKAmif9jTvB_jKApWD8rMbwho9OYlhTj4wA6YNErdpkUl6KDdlUq2Cw6rTc3OhWlf5GRqHdz_A99Vt2KbQEOQl2p48S1YXlTNsgrlJRxa8GSim5aESXbXpwTfnEsV1aNjzIRdamTrFsTj1Vyj6AN3mA2mvzJuyX8ZJ_0YZzceJgz0uqv6UPeEBC4v-3OCqonlxt0Ov6E_xaAxd3pP0ECrEhV1DUVrcDoXpBSS36NJ61Vk6JPUHXBKmeN-zjJzYN11RfvfeNG'),

('Diseño de Experiencia de Usuario', 'Crea interfaces intuitivas y memorables centradas en las necesidades del usuario final.', '90 horas', 'Laura Fernández', 499.00, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDl0Nruo_mbwLPXSBInSgpMJVHZnWHDeJrBwzqjkzV3iDpzKCGFoFKMnG5s5fkwRttgZS5BoRc09VyAj345hO_GJ__1t5m2FR1ChM3SpwXDMS79kU95iSXc7LUO2EDsd6irDzJ99Z8CqJfgFEPscJxqJf0-zfj3xZNCVvnQwSYksjtgoEs0kfqIWygZ3uI-JjLlE-2XPN9fPPDbjKnmHUADRZ945Vyd77ll_hzWoG-SqZhQ8f-xI4Gkb3sBuXd7wd5zeeNntGDExVQV'),

('Análisis de Datos con Python', 'Aprende a transformar grandes volúmenes de datos en información estratégica para la toma de decisiones.', '100 horas', 'David López', 549.00, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBJVCuQrKAmif9jTvB_jKApWD8rMbwho9OYlhTj4wA6YNErdpkUl6KDdlUq2Cw6rTc3OhWlf5GRqHdz_A99Vt2KbQEOQl2p48S1YXlTNsgrlJRxa8GSim5aESXbXpwTfnEsV1aNjzIRdamTrFsTj1Vyj6AN3mA2mvzJuyX8ZJ_0YZzceJgz0uqv6UPeEBC4v-3OCqonlxt0Ov6E_xaAxd3pP0ECrEhV1DUVrcDoXpBSS36NJ61Vk6JPUHXBKmeN-zjJzYN11RfvfeNG'),

('Liderazgo y Soft Skills', 'Desarrolla las habilidades interpersonales necesarias para liderar organizaciones en la era digital.', '70 horas', 'Patricia Sánchez', 429.00, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDl0Nruo_mbwLPXSBInSgpMJVHZnWHDeJrBwzqjkzV3iDpzKCGFoFKMnG5s5fkwRttgZS5BoRc09VyAj345hO_GJ__1t5m2FR1ChM3SpwXDMS79kU95iSXc7LUO2EDsd6irDzJ99Z8CqJfgFEPscJxqJf0-zfj3xZNCVvnQwSYksjtgoEs0kfqIWygZ3uI-JjLlE-2XPN9fPPDbjKnmHUADRZ945Vyd77ll_hzWoG-SqZhQ8f-xI4Gkb3sBuXd7wd5zeeNntGDExVQV');
